{
 "title": "Conference App",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Persistence metrics", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Neo4j memory consumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Memory %" }
   ],
   "targets": [
    {
     "expr": "neo4j_vm_heap_max / neo4j_vm_heap_used",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Neo4j accumulated processing time (1min rate)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_bolt_accumulated_processing_time_total[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Backend metrics", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Backend Heap memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Backend Non-Heap memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Backend total memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(jvm_memory_used_bytes)", "legendFormat": "used" },
    {
     "expr": "sum(jvm_memory_committed_bytes)",
     "legendFormat": "committed"
    },
    { "expr": "sum(jvm_memory_max_bytes)", "legendFormat": "max" }
   ]
  },
  {
   "title": "Backend CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "CPU %" }
   ],
   "targets": [
    { "expr": "system_cpu_usage * 100", "legendFormat": "system" },
    { "expr": "process_cpu_usage * 100", "legendFormat": "process" },
    {
     "expr": "avg_over_time(process_cpu_usage[1h]) * 100",
     "legendFormat": "process-1h"
    }
   ]
  },
  {
   "title": "Backend API request count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri=~\"/api/.*\"}",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Backend API request time (1min rate)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=~\"/api.*\"}[1m]) / rate(http_server_requests_seconds_count{uri=~\"/api.*\"}[1m])",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}