apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-metrics-servicemonitor
  namespace: {{ .Values.servicemonitor.metadata.namespace }}
  labels:
    release: {{ .Values.servicemonitor.metadata.labels.release }}
spec:
  endpoints:
    - path: /actuator/prometheus
      port: http
      interval: 15s
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
