image:
  repository: rjaniak/pac2020
  tag: conference-backend-1.0
  pullPolicy: Always
serviceAccount:
  name: backend
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
ingress:
  enabled: true
  annotations: {
    nginx.ingress.kubernetes.io/enable-cors: "true"
  }
  hosts:
    - host: backend.minikube
      paths:
        - "/"
  tls:
    - secretName: tls-secret
      hosts:
        - backend.minikube