image:
  # TODO: from harbor.prodyna.com
  repository: rjaniak/private/conference-frontend
  pullPolicy: IfNotPresent
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
ingress:
  enabled: true
  hosts:
    - host: frontend.minikube
      paths:
        - "/"
  tls:
    - secretName: tls-secret
      hosts:
        - frontend.minikube