keycloak:
  existingSecret: keycloak-access
  existingSecretKey: password
  persistence:
    dbVendor: mariadb
    dbHost: keycloak-mariadb
    dbPort: 3306
    existingSecret: keycloak-mariadb-access
    existingSecretUsernameKey: username
    existingSecretPasswordKey: password
  ingress:
    enabled: true
    path: /
    servicePort: http
    hosts:
      - keycloak.minikube
    tls:
     - hosts:
         - keycloak.minikube
       secretName: tls-secret
  extraVolumes: |
    - name: realm-pac
      secret:
        secretName: keycloak-realm-pac
  extraVolumeMounts: |
    - name: realm-pac
      mountPath: "/realm/"
      readOnly: true
  extraArgs: -Dkeycloak.import=/realm/realm-pac.json
