core:
  persistentVolume:
    size: 1Gi
metrics:
  prometheus:
    enabled: true
    endpoint: 0.0.0.0:2004
readReplica:
  autoscaling:
    enabled: true
    targetAverageUtilization: 70
    minReplicas: 1
    maxReplicas: 3
acceptLicenseAgreement: "yes"
imageTag: "4.1.0-enterprise"